name: Pytest with Pipenv & Docker
# workflow triggered by any push on any branch
on: [push]
jobs:
  build:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
     
    steps: 
    - name: Install docker
      run: |
        pip install --ignore-installed docker docker-compose
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; 
        pip install docker-compose;
        
    - name: Test with pytest
      run: |
          python -m unittest discover tests
    # runs within your Docker container
    container:
      image: docker://python:3-alpine
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
