name: Pytest with Pipenv & Docker
# workflow triggered by any push on any branch
on: [push]
jobs:
  build:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    # runs within your Docker container
    container:
      image: docker://python:3-alpine
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; 
        
    - name: Test with pytest
      run: |
          python -m unittest discover tests
